services:
  local-postgres-service:
    container_name: local-postgresql
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ketflix_user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: ketflix_db
    ports:
      - "5001:5432"
    volumes:
      - local-postgres-volume:/var/lib/postgresql/data
    networks:
      - local-postgres-network

volumes:
  local-postgres-volume:

networks:
  local-postgres-network: